name: Update docs

on:
  push:
    branches: [ master ]

jobs:
  update-docs:
    runs-on: ubuntu-24.04
    name: "Update website documentation"

    steps:
      - name: Create repository dispatch event
        if: github.ref == 'refs/heads/master'
        env:
          GITHUB_TOKEN: ${{ secrets.WEBSITE_PUSH_COMMIT_GITHUB_TOKEN }}
        run: |
          gh api repos/ArkScript-lang/website/dispatches --raw-field event_type=my_update_docs
